name: Test

on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        python-version:
          - "2.7"
          - "3.5"
          - "3.7"
          - "3.8"
          - "3.10"
          - "3.13"
    runs-on: ubuntu-latest
    container:
      image: python:${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v3
    - name: Install SSH
      run: |
        apt-get update -qq
        apt-get install -qq openssh-client openssh-server
    - run: pip install setuptools
    - run: pip install contextlib2
      if: ${{ startsWith(matrix.python-version, '2.') }}
    - name: Set up SSH
      run: .ci/setup_ssh.sh
    - run: pip install -e .
    - run: SCPPY_PORT=10022 python test.py
